### PR TITLE
Updated Dialog Prompts for Clarity

### PR DESCRIPTION
**Pull request by mattyrowey**
Updated the dialog in waitForUser, getBoolean, exit, and print commands to improve the clarity of each description.

The updated dialog is consistent with all three "Analyse Neuron" functions.

Only dialog boxes have been updated.

I have tested both macros and have not ran into any errors while running them. I also get the same results when running these macros compared to the current version of GAT.

### CODE REVIEW

**Comment by pr4deepr** [comment]
could you synchronize your fork with changes I've made recently?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by mattyrowey** [comment]
Yes, I've just synchronized my fork. 
Do I need to resubmit a pull request or will it be updated now?

**Comment by pr4deepr** [comment]
It should update automatically..

On your branch, you can see:

image


Earlier it said 2 commits ahead and also had commits behind, which meant it wasn't in sync..


Thanks Matt!

**Comment by mattyrowey** [comment]
Ok perfect, thanks for explaining. I did notice that!

**Comment by pr4deepr** [comment]
Just checking if you've tested the code?

**Comment by mattyrowey** [comment]
I had tested it prior to syncing prior to syncing just now and it all worked fine.

I can test it again shortly with the new updates.

**Review by pr4deepr — APPROVED** [review]

**Pull request merged**
